version: "3.9"

services:
  api:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: ./web
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    name: coder-view-net