version: "3.9"

services:
  api:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: ./web
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    name: coder-view-net